services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: youtube
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  server:
    build: ./src
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./src:/usr/src/app
    env_file:
      - ./src/.env

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
